config/routes.rb
Rails.application.routes.draw do
  get 'sessions/sign_in'
  delete 'sessions/sign_out'

  get 'auth/google_oauth2/callback' => 'sessions#google_oauth2_callback'
  post 'auth/google_oauth2/callback' => 'sessions#google_oauth2_callback'
  get 'auth/developer/callback' => 'sessions#developer_callback'
  post 'auth/developer/callback' => 'sessions#developer_callback'

  get 'auth/failure' => 'sessions#failure'

  resources :employees

end

app/models/employee.rb
class EmailValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, value)
    unless value =~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
      record.errors[attribute] << (options[:message] || "you typed in is not a correct email")
    end
  end
end

class Employee < ActiveRecord::Base

  attr_accessor :user_name, :credit_card_nr, :expiration_date

  validates :firstname, :lastname, :user_name, :expiration_date, presence: true, length: { maximum: 30 }
  validates :credit_card_nr, presence: true, length: { maximum: 30 }, numericality: { only_integer: true }
  validates :city, :street, :position, length: { maximum: 20 }
  validates :email, presence: true, email: true, length: { maximum: 30 }
  validates :post_code, :street_nr, presence: true, length: { maximum: 8 }, numericality: { only_integer: true }
  validates :pkz, length: { maximum: 4 }, numericality: { only_integer: true, allow_blank: true }
  validates :telephone, length: { minimum: 3, maximum: 25 }, numericality: { only_integer: true, allow_blank: true }
  validates :room_number, length: { maximum: 4 }, numericality: { only_integer: true, allow_blank: true }
  validates :social_security_numer, length: { maximum: 15 }, numericality: { only_integer: true, allow_blank: true }
  validate :expiration_date_cannot_be_in_the_past

  def expiration_date_time
    self.expiration_date
  end

  def expiration_date_time=(text)
    self.expiration_date = text.to_date
  end

  def set_attributes_from_social_media_service(json)
    self.social_network_user_id = json['Id']
    self.user_name = json['UserName']
    self.credit_card_nr = json['CreditCardNr']
    self.expiration_date = json['ExpirationDate'].to_date
  end

  private

  def expiration_date_cannot_be_in_the_past
    if self.expiration_date_time.present? && self.expiration_date_time < Date.today
      errors.add(:expiration_date, "can't be in the past")
    end
  end    
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  include Swagger::Docs::ImpotentMethods

  before_filter :authenticate_user!, except: [:index, :show]
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  swagger_controller :employees, "Employee Management"

  swagger_api :index do
    summary "Fetches all employees"
    notes "This lists all the active users"
  end

  swagger_api :show do
    consumes ["application/json"]
    summary "Fetches a single employee item"
    param :path, :id, :integer, :optional, "User Id"
  end

  swagger_api :create do
    summary "Creates a new employee"
    notes "This creates a new employee and saves it to the database"
    consumes ["application/json"]
    param :header, 'X-CSRF-Token', :string, :required, 'X-CSRF-Token'
    param :body, :body, :employee, :required, "Employee object"
    response :ok, "Employee was successfully created."
    response :unauthorized
    response :unprocessable_entity
  end

  swagger_api :update do
    summary "Updates an existing employee"
    notes "This updates an existing employee and saves the changes to the database"
    consumes ["application/json"]
    param :header, 'X-CSRF-Token', :string, :required, 'X-CSRF-Token'
    param :path, :id, :integer, :required, "User Id"
    param :body, :body, :employee, :required, "Employee object"
    response :ok, "Employee was successfully updated."
    response :unauthorized
    response :unprocessable_entity
  end

  swagger_api :destroy do
    summary "Deletes an existing employee"
    notes "This deletes an existing employee from the database"
    consumes ["application/json"]
    param :header, 'X-CSRF-Token', :string, :required, 'X-CSRF-Token'
    param :path, :id, :integer, :required, "User Id"
    response :ok, "Employee was successfully deleted."
    response :unauthorized
  end

  swagger_model :employee do
    description "employee object"
    property :id, :integer, :required, "User Id"
    property :user_name, :string, :optional, "User name"
    property :firstname, :string, :optional, "First name"
    property :lastname, :string, :optional, "Last name"
    property :pkz, :string, :optional, "PKZ"
    property :street, :string, :optional, "Street"
    property :street_nr, :integer, :optional, "Street Nr" 
    property :post_code, :integer, :optional, "Postcode" 
    property :city, :string, :optional, "City" 
    property :country, :string, :optional, "Country"  
    property :position, :string, :optional, "Position in Company"
    property :room_number, :string, :optional, "Room number" 
    property :superior_id, :string, :optional, "Superior ID" 
    property :telephone, :string, :optional, "Telephone number" 
    property :email, :string, :optional, "Email" 
    property :social_security_numer, :string, :optional, "Social security number"
    property :credit_card_nr, :string, :optional, "Credit card number"
    property :expiration_date, :string, :optional, "Credit card expiration date"
  end


  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
    if @employee.user_name.blank?
      flash.now[:notice] = "Social Network Service is not available or the user is not registered on the Social Network Service"
    end
  end

  # GET /employees/new
  def new
    @employees = Employee.all
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
    @employees = Employee.all
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    
    respond_to do |format|
      begin
        ActiveRecord::Base.transaction do
          @employee.save!
          uri = URI.parse("http://socialnetworkusers.azurewebsites.net/api/Users")
          http = Net::HTTP.new(uri.host, uri.port)
          request = Net::HTTP::Post.new(uri.path, 'Content-Type' => 'application/json')
          json = { :UserName => @employee.user_name,   
                  :FirstName => @employee.firstname, 
                  :LastName => @employee.lastname, 
                  :Email => @employee.email, 
                  :ExpirationDate => @employee.expiration_date.to_time.iso8601,
                  :Street => @employee.street,
                  :StreetNr => @employee.street_nr,
                  :PostCode => @employee.post_code,
                  :City => @employee.city,
                  :CreditCardNr => @employee.credit_card_nr,
                  :Country => @employee.country}.to_json
          request.body = json
          begin
            response = http.request(request)
          rescue
            format.html { redirect_to @employee, notice: 'Employee was successfully created but social network could not be reached.' }
            format.json { render :show, status: :ok, location: @employee }
            return
          end

          if response.code == '201'
            @employee.set_attributes_from_social_media_service JSON.parse(response.body)['user']
            @employee.save!
            format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
          else
            format.html { redirect_to @employee, notice: 'Employee was successfully created but could not be created in the social network.' }
          end  
          format.json { render :show, status: :created, location: @employee }
        end
      rescue ActiveRecord::RecordInvalid => exception
        @employees = Employee.all
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update

    respond_to do |format|
      if @employee.update(employee_params)
        # using other micro-service to update user data
        uri = URI.parse("http://socialnetworkusers.azurewebsites.net/api/Users/#{@employee.social_network_user_id}")
        http = Net::HTTP.new(uri.host, uri.port)
        request = Net::HTTP::Put.new(uri.path, 'Content-Type' => 'application/json')
        json = { :Id => @employee.social_network_user_id,
                 :UserName => @employee.user_name,
                 :FirstName => @employee.firstname, 
                 :LastName => @employee.lastname, 
                 :Email => @employee.email, 
                 :ExpirationDate => @employee.expiration_date.to_time.iso8601,
                 :Street => @employee.street,
                 :StreetNr => @employee.street_nr,
                 :PostCode => @employee.post_code,
                 :City => @employee.city,
                 :CreditCardNr => @employee.credit_card_nr,
                 :Country => @employee.country}.to_json
        request.body = json
        begin
          response = http.request(request)
        rescue
          format.html { redirect_to @employee, notice: 'Employee was successfully updated but social network could not be reached.' }
          format.json { render :show, status: :ok, location: @employee }
          return
        end

        if response.code == '204'
          format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        else 
          format.html { redirect_to @employee, notice: 'Employee was successfully updated but could not be updated in the social network.' }
        end
        format.json { render :show, status: :ok, location: @employee }
        
      else
        @employees = Employee.where.not(:id => @employee.id)
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy

    uri = URI.parse( "http://socialnetworkusers.azurewebsites.net/api/Users/#{@employee.social_network_user_id}" )
    request = Net::HTTP::Delete.new(uri.path)
    http = Net::HTTP.new(uri.host, uri.port)

    respond_to do |format|
      begin
        response = http.request(request)
      rescue
        format.html { redirect_to employees_url, notice: 'Employee was successfully deleted but social network could not be reached.' }
        format.json { head :no_content }
        return
      end

      if response.code == '200'
        format.html { redirect_to employees_url, notice: 'Employee was successfully deleted.' }
      else
        format.html { redirect_to employees_url, notice: 'Employee was successfully deleted but was not removed from the social network.' }
      end
      format.json { head :no_content }
     
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
      if @employee.social_network_user_id
        uri = URI.parse("http://socialnetworkusers.azurewebsites.net/api/Users/#{@employee.social_network_user_id}" )
        http = Net::HTTP.new(uri.host, uri.port)
        request = Net::HTTP::Get.new(uri.path)
        begin
          response = http.request(request)
          if response.code == '200'
            social_network_user = JSON.parse(response.body)
            @employee.set_attributes_from_social_media_service(social_network_user)
          else
            logger.error 'Social network service is not available.'
          end
        rescue
          logger.error 'Social network service is not available.'
        end
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:firstname, :lastname, :pkz, :street, :street_nr, :post_code, :city, :country, :position, :room_number, :superior_id, :telephone, :email, :social_security_numer, :user_name, :credit_card_nr, :expiration_date_time)
    end

    def authenticate_user!
      unless session['google_auth_data']
        respond_to do |format|

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<%= form_for(@employee) do |f| %>
  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% @employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_name %><br>
    <%= f.text_field :user_name %>
  </div>
  <div class="field">
    <%= f.label :firstname %><br>
    <%= f.text_field :firstname %>
  </div>
  <div class="field">
    <%= f.label :lastname %><br>
    <%= f.text_field :lastname %>
  </div>
  <div class="field">
    <%= f.label :pkz %><br>
    <%= f.text_field :pkz %>
  </div>
  <div class="field">
    <%= f.label :street %><br>
    <%= f.text_field :street %>
  </div>
    <div class="field">
    <%= f.label :street_nr %><br>
    <%= f.text_field :street_nr %>
  </div>
  <div class="field">
    <%= f.label :post_code %><br>
    <%= f.text_field :post_code %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :position %><br>
    <%= f.text_field :position %>
  </div>
  <div class="field">
    <%= f.label :room_number %><br>
    <%= f.text_field :room_number %>
  </div>
  <div class="field">
    <%= f.label :superior_id %><br>
    <%= f.select(:superior_id, @employees.collect {|e| [e.firstname + " " + e.lastname, e.id]}, {include_blank: true}) %>
  </div>
  <div class="field">
    <%= f.label :telephone %><br>
    <%= f.text_field :telephone %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :social_security_numer %><br>
    <%= f.text_field :social_security_numer %>
  </div>
  <div class="field">
    <%= f.label :credit_card_nr %><br>
    <%= f.text_field :credit_card_nr %>
  </div>
  <div class="field">
    <%= f.label :expiration_date %><br>
    <%= f.date_field :expiration_date_time %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing Employee</h1>

<%= render 'form' %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Employees</h1>

<table>
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Pkz</th>
      <th>Street</th>
      <th>Street_Nr</th>
      <th>Post_Code</th>
      <th>City</th>
      <th>Country</th>
      <th>Position</th>
      <th>Room number</th>
      <th>Superior</th>
      <th>Telephone</th>
      <th>Email</th>
      <th>Social security numer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.firstname %></td>
        <td><%= employee.lastname %></td>
        <td><%= employee.pkz %></td>
        <td><%= employee.street %></td>
        <td><%= employee.street_nr %></td>
        <td><%= employee.post_code %></td>
        <td><%= employee.city %></td>
        <td><%= employee.country %></td>
        <td><%= employee.position %></td>
        <td><%= employee.room_number %></td>
        <td><%= employee.superior_id %></td>
        <td><%= employee.telephone %></td>
        <td><%= employee.email %></td>
        <td><%= employee.social_security_numer %></td>
        <td><%= link_to 'Show', employee %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
        <td><%= link_to 'Delete', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employee', new_employee_path %>

app/views/employees/new.html.erb
<h1>New Employee</h1>

<%= render 'form' %>

<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @employee.user_name %>
</p>

<p>
  <strong>Firstname:</strong>
  <%= @employee.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @employee.lastname %>
</p>

<p>
  <strong>Pkz:</strong>
  <%= @employee.pkz %>
</p>

<p>
  <strong>Street:</strong>
  <%= @employee.street %>
</p>

<p>
  <strong>Street_Nr:</strong>
  <%= @employee.street_nr %>
</p>

<p>
  <strong>Post_Code:</strong>
  <%= @employee.post_code %>
</p>

<p>
  <strong>City:</strong>
  <%= @employee.city %>
</p>

<p>
  <strong>Country:</strong>
  <%= @employee.country %>
</p>

<p>
  <strong>Position:</strong>
  <%= @employee.position %>
</p>

<p>
  <strong>Room number:</strong>
  <%= @employee.room_number %>
</p>

<p>
  <strong>Superior:</strong>
  <%= @employee.superior_id %>
</p>

<p>
  <strong>Telephone:</strong>
  <%= @employee.telephone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @employee.email %>
</p>

<p>
  <strong>Social Security Number:</strong>
  <%= @employee.social_security_numer %>
</p>

<p>
  <strong>Credit Card Nr:</strong>
  <%= @employee.credit_card_nr %>
</p>

<p>
  <strong>Expiration Date:</strong>
  <%= @employee.expiration_date %>
</p>

<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>